### ISSUE TITLE
Full Screen

### ISSUE THREAD

**Issue by panda939** [sagynbek/jutsu-extension#1]
Не открывает на весь экран автоматически

**Comment by sagynbek** [comment]
@panda939 здрастуйте, во первых спасибо что используете наше расшерение.
Я много раз пытался добавить эту функцию, но не мог изза того что блокируюсь браузером. Оно не открывает на весь экран автоматически изза [этой проблемы с браузером](https://github.com/sagynbek/jutsu-extension/blob/49d8c1dff95d4ff2c1cfa4dc4aa78ecb593d0722/src/inject/player/player.ts#L13). 
Если у вас есть какое то решение буду рад услышать

**Comment by panda939** [comment]
@sagynbek а разве нельзя с вызвать нажатие клавиши "F" после загрузки страницы?

**Comment by sagynbek** [comment]
@panda939 да при нажатии на "F" должно сработать. Это конечно не автоматически, но наверное лучше чем ничего. 
Как вы думаете?

**Comment by panda939** [comment]
@sagynbek Это первое что пришло мне в голову когда я задумался над этим вопросом, после того как нашел ваше замечательное расширение)

**Comment by panda939** [comment]
Я несилен в JS, да и знаю про ограничения браузером на выполнение что-то подобного. В итоге от нежелания погружаться в создание расширений для Chrome и писать код на коленке я нашел ваше расширение.  
А чуть позже обнаружил и Github и попытки реализовать данный функционал. 
Так как вы сделать данное расширение я бы не смог. По этому и обратился с данной просьбой.

Благодарю за своевременную обратную связь. Надеюсь вы сможете прикрутить костыли  для работы данного функционала 😄

**Comment by sagynbek** [comment]
@panda939 спасибо за понимание и за ваш совет. Мне понравилось решение с помощью нажатия на клавишу, так как вы как пользователь будете пользоваться этой функцией, я добавлю эту функцию как можно скорее
Желаю вам здоровья, ждите от меня новостей

**Comment by panda939** [comment]
@sagynbek Thx
